application:
  name: work-auth
  ip: 0.0.0.0
  port: 8091
  env: dev
  version: v1.0.0
  debug:
    enable: true
    username: admin
    password: admin
cloud:
  nacos:
    enable: false
    ip: 127.0.0.1
    port: 8848
    namespace: 7cd8da2f-1861-4c25-8afe-789523b00e14
    username: nacos
    password: nacos
  zookeeper:
    enable: false
    ip: 127.0.0.1
    port: 2181
    namespace: public
    username: zookeeper
    password: zookeeper
    group: DEFAULT_GROUP
redis:
  enable: true
  ip: 127.0.0.1
  port: 6379
  db: 0
db:
  enable: true
  type: postgres
  ip: 127.0.0.1
  port: 5432
  dbname: work
  username: postgres
  password: 123456